---
groups:
- name: main
  jobs:
  - build-docker-image
  - job-deploy-app

jobs:

- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: Taskmanager
    trigger: true
  - put: docker-image
    params:
      build: Taskmanager
      
- name: job-deploy-app
  serial: true
  plan:
  - get: Taskmanager
    trigger: true
    passed: 
      - build-docker-image
  - put: cf-env
    params:
      manifest: Taskmanager/manifest.yml
      path: Taskmanager
  
resources:
- name: Taskmanager
  type: git
  source:
    uri: https://github.com/vc4017/Taskmanager.git
    branch: master
    
- name: cf-env
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: vc4017@gmail.com
    password: Venki@521
    organization: vc4017-org
    space: deployment
    skip_cert_check: true
- name: docker-image
  type: docker-image
  source:
    email: tovenki.ch@gmail.com
    username: venki521
    password: venki@521
    repository: venki521/Taskmanager
    
